http://localhost:4000/games/1
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTM0NDA3MjM1LCJleHAiOjE1MzQ0MjE2MzV9.ukmjASayO7noNi7uPg9c-dWXrGWtyQ3idnj4ts9gkuE

###
http://localhost:4000/games
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTM0NDA3MjM1LCJleHAiOjE1MzQ0MjE2MzV9.ukmjASayO7noNi7uPg9c-dWXrGWtyQ3idnj4ts9gkuE


############ CREATE GAME ###############
### Hajime
POST http://localhost:4000/games
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTM0NDA3MjM1LCJleHAiOjE1MzQ0MjE2MzV9.ukmjASayO7noNi7uPg9c-dWXrGWtyQ3idnj4ts9gkuE
############ UPDATE GAME ###############
PATCH http://localhost:4000/games/25
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTM0NDA3MjM1LCJleHAiOjE1MzQ0MjE2MzV9.ukmjASayO7noNi7uPg9c-dWXrGWtyQ3idnj4ts9gkuE

{
  "position":{
    "rowIndex": 0,
    "columnIndex": 4
  } 
}
############ UPDATE GAME ###############
PATCH http://localhost:4000/games/29
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNTM0NDExNjkwLCJleHAiOjE1MzQ0MjYwOTB9.OHI3Oc2Y_uRWE2k_O-FwbKlgk7tZYLi0nRm4UHqngZw

{
  "gameId": 2,
  "position":{
    "rowIndex": 2,
    "columnIndex": 2
  } 
}
###
### Somebody
POST http://localhost:4000/games
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNTM0MzU5MzM4LCJleHAiOjE1MzQzNzM3Mzh9.HD2mJTM0qL97AOTVPSJTINsrO3kWJzaPWZnJfHRLlvQ

### Somebody
POST http://localhost:4000/games/25/players
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNTM0NDExNjkwLCJleHAiOjE1MzQ0MjYwOTB9.OHI3Oc2Y_uRWE2k_O-FwbKlgk7tZYLi0nRm4UHqngZw













###

POST http://localhost:4000/logins
Content-Type: application/json

{
  "email": "hajime.doublebass@gmail.com",
  "password":"testtest"
}
###

POST http://localhost:4000/logins
Content-Type: application/json

{
  "email": "hajime.doublebasss@gmail.com",
  "password":"testtest"
}

####
POST http://localhost:4000/logins
Content-Type: application/json

{
  "firstName":"another",
  "lastName": "test",
  "email": "asht@gmail.com",
  "password":"ashtasht"
}

###
POST http://localhost:4000/users
Content-Type: application/json

{
  "firstName":"Hajime",
  "lastName": "Suzuki",
  "email": "hajime.doublebass@gmail.com",
  "password":"testtest"
}
###
POST http://localhost:4000/users
Content-Type: application/json

{
  "firstName":"Test",
  "lastName": "somebody",
  "email": "test@gmail.com",
  "password":"testtest"
}
###
POST http://localhost:4000/users
Content-Type: application/json

{
  "firstName":"another",
  "lastName": "test",
  "email": "asht@gmail.com",
  "password":"ashtasht"
}